# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
#pod 'VKVideoPlayer', '~> 0.1.4'

pod 'SDWebImage', '~>3.7'
pod 'YTKNetwork', '~> 0.5.0'
pod 'MJExtension', '~> 3.0.7'
pod 'MJRefresh', '~> 3.0.8'
 
#pod 'VKVideoPlayer', '~> 0.1.4'
####### VKVideoPlayer ########
#VKVideoPlayer包含以下的库，但是VKVideoPlayer在人人美剧已经自定义了，所以直接拷贝过来
pod 'CocoaHTTPServer', '~> 2.3'#已经有了
pod 'DTCoreText', '~> 1.6.17'
#pod 'AFNetworking', '1.3.3'
pod 'CocoaLumberjack', '~> 1.7.0'
pod 'VKFoundation', '0.1.1'
####### VKVideoPlayer ########







