# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'VKVideoPlayerPro' do

end

target 'VKVideoPlayerProTests' do

end

target 'VKVideoPlayerProUITests' do

end

