# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'AFNetworking'

target 'Swift_Weather' do

end

target 'Swift_WeatherTests' do

end

target 'Swift_WeatherUITests' do

end

