source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 2.0'
pod 'SwiftyJSON', '~> 2.3.2'
pod 'SDWebImage', '~>3.7'
pod 'MJExtension', '~> 3.0.10'/Users/tengfei/github/iOS_Demo/ZhiHuPlus2.0/ZhiHuPlus2.0/Base.lproj/LaunchScreen.storyboard
/Users/tengfei/github/iOS_Demo/ZhiHuPlus2.0/ZhiHuPlus2.0/Info.plist